{% set version = "3.0+sirius6.1.0" %}
{% set name = "r-sirius-ms" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://github.com/sirius-ms/sirius-client-openAPI/archive/refs/tags/{{ version }}.zip
  sha256: 46e8a364c23bd6c64ff0627cb72c0c955322f5f365d418e49dfdd175263fe764

build:
  noarch: generic
  number: 0
  merge_build_host: True  # [win]
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - m2-zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base >=4.0.0
    - r-jsonlite
    - r-httr2
    - r-r6
    - r-base64enc
    - r-stringr
    - r-processx
  run:
    - r-base >=4.0.0
    - r-jsonlite
    - r-httr2
    - r-r6
    - r-base64enc
    - r-stringr
    - r-processx
    - sirius-ms >=6.1.0

test:
  files:
    - Kaempferol.ms
  commands:
    - sh run_test.sh           # [not win]
    - call run_test.bat        # [win]

about:
  home: https://github.com/sirius-ms/sirius-client-openAPI/tree/master/client-api_r
  summary: 'RSirius: R library for SIRIUS MS/MS analyses software.'
  description: |
    R client for the SIRIUS (local) REST API (OpenAPI) that provides the full functionality of the SIRIUS 
    MS/MS analyses software including its web based features as background service.
  license: Apache-2.0
  license_file: client-api_r/LICENSE.txt
  doc_url: https://v6.docs.sirius-ms.io/
  dev_url: https://github.com/sirius-ms/sirius-client-openAPI/tree/master/client-api_r

extra:
  recipe-maintainers:
    - mfleisch
    - joXemMx
